### ISSUE TITLE
Setup tests

### ISSUE THREAD

**Issue by dryan** [RagtagOpen/phone-number-validator#2]
We need to setup several tests to insure future changes don't inadvertently break the API.

Specifically we need:

* [ ] Tests with valid phone numbers that return expected information for each property
* [ ] Tests with numbers that are too short
* [ ] Tests with numbers that are too long
* [ ] Tests with numbers that have an invalid area code (200 for example)

**Comment by iandees** [comment]
Tests were added in #5.
